// frameworks/react-pull/src/app.tsx
import "./index.css";
import { TreeProvider, useTree } from "@/tree-provider.tsx";
import { NodeAttributes } from "@/node-attributes.tsx";
import { Tree } from '@/tree.tsx'

export function App() {
  return (
    <TreeProvider>
      <Main />
    </TreeProvider>
  );
}

function Main() {
  const tree = useTree();
  return (
    <main className="grid grid-cols-2 p-4">
      <Tree node={tree.root} />
      <NodeAttributes />
    </main>
  );
}

export default App;

// frameworks/vue-signals/src/App.vue
<script setup lang="ts">
import { storeToRefs } from "pinia";
import { useTreeStore } from "@/stores/useTree.ts";
import Tree from "@/components/Tree.vue";
import NodeAttributes from "@/components/NodeAttributes.vue";

const { tree } = storeToRefs(useTreeStore());
</script>
<template>
  <main class="grid grid-cols-2 p-4">
    <Tree :node="tree" />
    <NodeAttributes />
  </main>
</template>

<style scoped></style>
