// frameworks/react-pull/src/tree-node.tsx
import type { NodePath, TreeNode } from "@/model.ts";
import { useTree } from "@/tree-provider.tsx";

type Props = {
  node: TreeNode;
  path: NodePath;
};

export function TreeNode({ node, path }: Props) {
  const tree = useTree();
  const isSelected = false;
  const isEdited = tree.useIsEdited(path);

  return (
    <div className="ml-5">
      <div
        className={`flex items-center w-fit cursor-pointer py-2 min-h-8 rounded pr-2 ${isSelected ? "bg-blue-100" : ""}`}
      >
        {node.children.length ? (
          <button
            className="toggle-button p-1 mr-2 w-6 h-6 rounded hover:bg-gray-100
               focus-visible:outline-2 focus-visible:outline-blue-500 focus-visible:outline-offset-2
               transition-colors duration-200 flex items-center justify-center"
            onClick={() => tree.toggleNodeExpansion(path)}
          >
            <span
              className={`toggle-icon text-xs text-gray-600 transition-transform duration-200 inline-block ${node.isExpanded ? "" : "-rotate-90"}`}
              data-testid={"expand:" + node.title}
            >
              ▼
            </span>
          </button>
        ) : (
          <span className="w-6 mr-2"></span>
        )}

        <span className="node-title text-sm text-gray-800 flex-1" title={node.title}>
          {node.title}
        </span>

        {isEdited && (
          <span className="ml-2 text-sm" data-testid={"pencil:" + node.title}>
            ✏️
          </span>
        )}
      </div>

      {node.isExpanded && node.children && (
        <div className="children-container border-l border-dashed border-gray-300 ml-3 pl-2">
          {node.children.map((child, index) => (
            <TreeNode key={index} node={child} path={[...path, index]} />
          ))}
        </div>
      )}
    </div>
  );
}

// frameworks/angular-signals/src/app/components/tree-node.ts
import { Component, computed, inject, input } from "@angular/core";
import { TreeNode } from "../model";
import { SelectedNodeProvider } from "../services/selected-node.provider";

@Component({
  selector: "tree-node",
  template: `
    <div class="ml-5" >
      <div class="flex items-center w-fit cursor-pointer py-2 min-h-8 rounded pr-2" [class]="isSelected() ? 'bg-blue-100' : ''" >
        @if (node().children.length) {
          <button
            class="toggle-button p-1 mr-2 w-6 h-6 rounded hover:bg-gray-100
               focus-visible:outline-2 focus-visible:outline-blue-500 focus-visible:outline-offset-2
               transition-colors duration-200 flex items-center justify-center"
            (click)="node().isExpanded.set(!node().isExpanded())"
          >
        <span
          class="toggle-icon text-xs text-gray-600 transition-transform duration-200 inline-block"
          [class]="node().isExpanded() ? '': '-rotate-90' "
          [attr.data-testid]="'expand:' + node().title"
        >
          ▼
        </span>
          </button>
        } @else {
          <span class="w-6 mr-2"></span>
        }

        <span
          (click)="this.selectedNodeProvider.selected.set(node())"
          class="node-title text-sm text-gray-800 flex-1"
          [title]="node().title"
        >{{ node().title }}</span>

        @if (node().isEdited()) {
          <span class="ml-2 text-sm" [attr.data-testid]="'pencil:' + node().title">✏️</span>
        }
      </div>

      <!-- Children Container -->
      @if (node().isExpanded() && node().children) {
        <div class="children-container border-l border-dashed border-gray-300 ml-3 pl-2">
          @for (child of node().children; track $index) {
            <tree-node
              [node]="child"
              class="child-node block"
            />
          }
        </div>
      }
    </div>
  `,
})
export class TreeNodeComponent {
  readonly selectedNodeProvider = inject(SelectedNodeProvider);
  readonly node = input.required<TreeNode>();

  readonly isSelected = computed(() =>
    Object.is(this.node(), this.selectedNodeProvider.selected()),
  );
}
