// frameworks/angular-push-node-map-euler-tour-segment-tree/src/app/app.ts
import { Component, computed, inject } from "@angular/core";
import { TreeNode } from "./model";
import { TreeNodeComponent } from "./components/tree-node";
import { NodeAttributesComponent } from "./components/node-attributes";
import { TreeStore } from "./services/tree-store.service";

@Component({
  selector: "app-root",
  template: `
    <main class="grid grid-cols-2 p-4">
      <div class="flex flex-col">
      @for (node of tree.flattened(); track node.id) {
        <tree-node [node]="node" />
      }
      </div> 
    <node-attributes />
    </main> 
  `,
  imports: [TreeNodeComponent, NodeAttributesComponent],
})
export class App {
  readonly tree = inject(TreeStore);
}

// frameworks/react-push-nodes-map/src/app.tsx
import "./index.css";
import { TreeProvider } from "./TreeContext";
import { TreeNode } from "./TreeNode";
import { NodeAttributes } from "./NodeAttributes";
import { Tree } from "./model";
import { useTree } from "./TreeContext";
import { tree } from "@/frontend.tsx";

function AppContent() {
  const { flattened } = useTree();

  return (
    <main className="grid grid-cols-2 p-4">
      <div className="flex flex-col">
        {flattened.map((node) => (
          <TreeNode key={node.id} node={node} />
        ))}
      </div>
      <NodeAttributes />
    </main>
  );
}

export function App() {
  const initialTree = Tree.fromDto(tree.data!);

  return (
    <TreeProvider initialTree={initialTree}>
      <AppContent />
    </TreeProvider>
  );
}
