// frameworks/angular-push-node-map-euler-tour-segment-tree/src/app/components/node-attributes.ts
import { Component, inject } from "@angular/core";
import { DisplayedTreeNodeAttr } from "../model";
import { TreeStore } from "../services/tree-store.service";

@Component({
  selector: "node-attributes",
  template: `
    <div class=" rounded-lg shadow-sm border border-gray-200 overflow-hidden">
      <div class="bg-gray-50 px-4 py-3 border-b border-gray-200">
        <h3 class="text-lg font-medium text-gray-800">
          {{ tree.selectedTitle() }}
        </h3>
      </div>
      
      @if (tree.attributes().length) {
        <div class="overflow-x-auto">
          <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider w-16">
                Edited
              </th>
              <th scope="col" class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Title
              </th>
              <th scope="col" class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Value
              </th>
              <th scope="col" class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Clear
              </th> 
            </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
                @for (attr of tree.attributes(); track $index) {
                  <tr class="hover:bg-gray-50 transition-colors duration-150">
                    <!-- Edited Column -->
                    <td class="px-4 py-3 whitespace-nowrap">
                      @if (attr.isEdited) {
                        <span>✏️</span>
                      }
                    </td>

                    <!-- Title Column -->
                    <td class="px-4 py-3">
                      <span class="text-sm font-medium text-gray-900">
                        {{ attr.title }}
                      </span>
                    </td>

                    <td class="px-4 py-3">
                      <div class="relative">
                        <input
                            [attr.data-testid]="attr.title"
                            type="text"
                            [value]="attr.value"
                            (input)="setValue(attr, $event)"
                            class="w-full px-3 py-2 border border-gray-300 rounded-md
                           focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500
                           text-sm transition-colors duration-200"
                        />
                      </div>
                    </td>
                    <!-- Clear Column -->
                    <td class="px-4 py-3 whitespace-nowrap">
                      @if (attr.isEdited) {
                        <button [attr.data-testid]="'clear:' + attr.title"
                                (click)="tree.clear(attr.parentId, attr.id)">↩️</button>
                      }
                    </td> 
                  </tr>
              }
            </tbody>
          </table>
        </div> 
      }
    </div>
  `,
})
export class NodeAttributesComponent {
  readonly tree = inject(TreeStore);

  setValue(attr: DisplayedTreeNodeAttr, event: Event): void {
    const value = (event.target as HTMLInputElement).value;
    this.tree.edit(attr.parentId, attr.id, value);
  }
}

// frameworks/react-push-nodes-map/src/NodeAttributes.tsx
import type { DisplayedTreeNodeAttr } from "./model";
import { useTree } from "./TreeContext";

export function NodeAttributes() {
  const { selectedTitle, attributes, edit } = useTree();

  const setValue = (attr: DisplayedTreeNodeAttr, event: React.ChangeEvent<HTMLInputElement>) => {
    const value = event.target.value;
    edit(attr.parentId, attr.id, value);
  };

  return (
    <div className="rounded-lg shadow-sm border border-gray-200 overflow-hidden">
      <div className="bg-gray-50 px-4 py-3 border-b border-gray-200">
        <h3 className="text-lg font-medium text-gray-800">{selectedTitle || ""}</h3>
      </div>

      {attributes.length > 0 && (
        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gray-50">
              <tr>
                <th
                  scope="col"
                  className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider w-16"
                >
                  Edited
                </th>
                <th
                  scope="col"
                  className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Title
                </th>
                <th
                  scope="col"
                  className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Value
                </th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {attributes.map((attr, index) => (
                <tr key={index} className="hover:bg-gray-50 transition-colors duration-150">
                  {/* Edited Column */}
                  <td className="px-4 py-3 whitespace-nowrap">
                    {attr.isEdited && <span>✏️</span>}
                  </td>

                  {/* Title Column */}
                  <td className="px-4 py-3">
                    <span className="text-sm font-medium text-gray-900">{attr.title}</span>
                  </td>

                  <td className="px-4 py-3">
                    <div className="relative">
                      <input
                        data-testid={attr.title}
                        type="text"
                        value={attr.value}
                        onChange={(e) => setValue(attr, e)}
                        className="w-full px-3 py-2 border border-gray-300 rounded-md
                           focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500
                           text-sm transition-colors duration-200"
                      />
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
